blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/LinoGoncalves/GoalCast/wiki
    about: Check the project wiki for guides and documentation
  - name: 💬 Discussions
    url: https://github.com/LinoGoncalves/GoalCast/discussions
    about: Ask questions and discuss ideas with the community
