name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-refinement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Template
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, the model doesn't account for..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        Add a new model that incorporates team fatigue based on fixture congestion:
        - Track days between matches
        - Adjust team strength parameters
        - Validate with historical data
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
    validations:
      required: false
      
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How will we know this feature is successful?
      placeholder: |
        - Improvement in Brier score by X%
        - Validated against last season's data
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
